# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionTitle', models.CharField(max_length=256, verbose_name='问题标题')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('questionDescription', models.TextField(default='', verbose_name='问题描述')),
                ('status', models.CharField(choices=[('0', '未提交'), ('1', '未处理'), ('2', '已处理')], default='0', max_length=1, verbose_name='问题状态')),
            ],
        ),
    ]
