# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-08 03:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseTime', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='endTime',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 11, 8, 3, 2, 53, 390097, tzinfo=utc), verbose_name='结束时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Question', verbose_name='文档来源'),
        ),
    ]
